# Background and foreground colors
background = #131520
foreground = #e5c3ce

# Standard colors
palette = 0=#131520
palette = 1=#d69991
palette = 2=#eaaba6
palette = 3=#f4b5ad
palette = 4=#99adde
palette = 5=#cea5c9
palette = 6=#a2c3f2
palette = 7=#e5c3ce

# Bright colors
palette = 8=#707177
palette = 9=#feb9af
palette = 10=#ffaca5
palette = 11=#ffb7aa
palette = 12=#b8ccff
palette = 13=#efbfec
palette = 14=#a0ceff
palette = 15=#ffc5de
