background            #131520
foreground            #e5c3ce

# black
color0  #131520
color8  #707177

# red
color1  #d69991
color9  #feb9af

# green
color2  #eaaba6
color10 #ffaca5

# yellow
color3  #f4b5ad
color11 #ffb7aa

# blue
color4  #99adde
color12 #b8ccff

# magenta
color5  #cea5c9
color13 #efbfec

#cyan
color6  #a2c3f2
color14 #a0ceff

#white
color7  #e5c3ce
color15 #ffc5de


